Repository konstellation-io/kai-processes, pull requests merged in 2023-11, with the labels that each got.

#23 Feature/minio config
  cronjob-trigger/app.yaml
  github-webhook-trigger/app.yaml
  gitlab-webhook-trigger/app.yaml
  grpc-trigger/app.yaml
  process-trigger/README.md
  process-trigger/app.yaml
  rest-trigger/app.yaml
Labels: size/s

#24 Feature: kafka trigger
  .github/workflows/test.yaml
  kafka-trigger/.golangci.yml
  kafka-trigger/Dockerfile
  kafka-trigger/README.md
  kafka-trigger/app.yaml
  kafka-trigger/config.yaml
  kafka-trigger/develop.Dockerfile
  kafka-trigger/go.mod
  kafka-trigger/go.sum
  kafka-trigger/main.go
  kafka-trigger/main_test.go
  kafka-trigger/minikube_build.sh
  kafka-trigger/sonar-project.properties
Labels: size/xl

#34 feature: update processes' go-sdk
  cronjob-trigger/config.yaml
  cronjob-trigger/go.mod
  cronjob-trigger/go.sum
  github-webhook-trigger/config.yaml
  github-webhook-trigger/go.mod
  github-webhook-trigger/go.sum
  gitlab-webhook-trigger/config.yaml
  gitlab-webhook-trigger/go.mod
  gitlab-webhook-trigger/go.sum
  grpc-trigger/config.yaml
  grpc-trigger/go.mod
  grpc-trigger/go.sum
  kafka-trigger/config.yaml
  kafka-trigger/go.mod
  kafka-trigger/go.sum
  process-trigger/config.yaml
  process-trigger/go.mod
  process-trigger/go.sum
  process-trigger/main.go
  rest-trigger/config.yaml
  rest-trigger/go.mod
  rest-trigger/go.sum
Labels: size/l

#35 feat: update dependencies
  cronjob-trigger/app.yaml
  cronjob-trigger/go.mod
  cronjob-trigger/go.sum
  github-webhook-trigger/app.yaml
  github-webhook-trigger/go.mod
  github-webhook-trigger/go.sum
  gitlab-webhook-trigger/app.yaml
  gitlab-webhook-trigger/go.mod
  gitlab-webhook-trigger/go.sum
  grpc-trigger/app.yaml
  grpc-trigger/go.mod
  grpc-trigger/go.sum
  kafka-trigger/app.yaml
  kafka-trigger/go.mod
  kafka-trigger/go.sum
  process-trigger/app.yaml
  process-trigger/go.mod
  process-trigger/go.sum
  rest-trigger/app.yaml
  rest-trigger/go.mod
  rest-trigger/go.sum
Labels: size/l
